<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DeviceApplication', 'mdmserver');

/**
 * BaseDeviceApplication
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $device_id
 * @property string $name
 * @property string $version
 * @property string $identifier
 * @property string $size
 * @property DeviceInventory $DeviceInventory
 * 
 * @method integer           getDeviceId()        Returns the current record's "device_id" value
 * @method string            getName()            Returns the current record's "name" value
 * @method string            getVersion()         Returns the current record's "version" value
 * @method string            getIdentifier()      Returns the current record's "identifier" value
 * @method string            getSize()            Returns the current record's "size" value
 * @method DeviceInventory   getDeviceInventory() Returns the current record's "DeviceInventory" value
 * @method DeviceApplication setDeviceId()        Sets the current record's "device_id" value
 * @method DeviceApplication setName()            Sets the current record's "name" value
 * @method DeviceApplication setVersion()         Sets the current record's "version" value
 * @method DeviceApplication setIdentifier()      Sets the current record's "identifier" value
 * @method DeviceApplication setSize()            Sets the current record's "size" value
 * @method DeviceApplication setDeviceInventory() Sets the current record's "DeviceInventory" value
 * 
 * @package    mdm-server
 * @subpackage model
 * @author     Dung Huynh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDeviceApplication extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('device_application');
        $this->hasColumn('device_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('version', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('identifier', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('size', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DeviceInventory', array(
             'local' => 'device_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}