<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DeviceInventory', 'mdmserver');

/**
 * BaseDeviceInventory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $device_name
 * @property string $manufacturer
 * @property string $product_name
 * @property string $device_type
 * @property string $registration_id
 * @property integer $enroll_status
 * @property string $version
 * @property string $organization
 * @property string $location
 * @property integer $platform
 * @property timestamp $purchase_date
 * @property timestamp $warranty_end
 * @property integer $user_id
 * @property string $owner_name
 * @property string $owner_email
 * @property string $udid
 * @property string $imei
 * @property string $wifi_mac_address
 * @property string $passcode
 * @property string $model
 * @property Doctrine_Collection $DeviceInventories
 * @property Doctrine_Collection $DeviceEventInventories
 * @property Doctrine_Collection $DeviceApplicationInventories
 * @property Doctrine_Collection $DeviceLocationInventories
 * @property Doctrine_Collection $DeviceProfiles
 * 
 * @method string              getDeviceName()                   Returns the current record's "device_name" value
 * @method string              getManufacturer()                 Returns the current record's "manufacturer" value
 * @method string              getProductName()                  Returns the current record's "product_name" value
 * @method string              getDeviceType()                   Returns the current record's "device_type" value
 * @method string              getRegistrationId()               Returns the current record's "registration_id" value
 * @method integer             getEnrollStatus()                 Returns the current record's "enroll_status" value
 * @method string              getVersion()                      Returns the current record's "version" value
 * @method string              getOrganization()                 Returns the current record's "organization" value
 * @method string              getLocation()                     Returns the current record's "location" value
 * @method integer             getPlatform()                     Returns the current record's "platform" value
 * @method timestamp           getPurchaseDate()                 Returns the current record's "purchase_date" value
 * @method timestamp           getWarrantyEnd()                  Returns the current record's "warranty_end" value
 * @method integer             getUserId()                       Returns the current record's "user_id" value
 * @method string              getOwnerName()                    Returns the current record's "owner_name" value
 * @method string              getOwnerEmail()                   Returns the current record's "owner_email" value
 * @method string              getUdid()                         Returns the current record's "udid" value
 * @method string              getImei()                         Returns the current record's "imei" value
 * @method string              getWifiMacAddress()               Returns the current record's "wifi_mac_address" value
 * @method string              getPasscode()                     Returns the current record's "passcode" value
 * @method string              getModel()                        Returns the current record's "model" value
 * @method Doctrine_Collection getDeviceInventories()            Returns the current record's "DeviceInventories" collection
 * @method Doctrine_Collection getDeviceEventInventories()       Returns the current record's "DeviceEventInventories" collection
 * @method Doctrine_Collection getDeviceApplicationInventories() Returns the current record's "DeviceApplicationInventories" collection
 * @method Doctrine_Collection getDeviceLocationInventories()    Returns the current record's "DeviceLocationInventories" collection
 * @method Doctrine_Collection getDeviceProfiles()               Returns the current record's "DeviceProfiles" collection
 * @method DeviceInventory     setDeviceName()                   Sets the current record's "device_name" value
 * @method DeviceInventory     setManufacturer()                 Sets the current record's "manufacturer" value
 * @method DeviceInventory     setProductName()                  Sets the current record's "product_name" value
 * @method DeviceInventory     setDeviceType()                   Sets the current record's "device_type" value
 * @method DeviceInventory     setRegistrationId()               Sets the current record's "registration_id" value
 * @method DeviceInventory     setEnrollStatus()                 Sets the current record's "enroll_status" value
 * @method DeviceInventory     setVersion()                      Sets the current record's "version" value
 * @method DeviceInventory     setOrganization()                 Sets the current record's "organization" value
 * @method DeviceInventory     setLocation()                     Sets the current record's "location" value
 * @method DeviceInventory     setPlatform()                     Sets the current record's "platform" value
 * @method DeviceInventory     setPurchaseDate()                 Sets the current record's "purchase_date" value
 * @method DeviceInventory     setWarrantyEnd()                  Sets the current record's "warranty_end" value
 * @method DeviceInventory     setUserId()                       Sets the current record's "user_id" value
 * @method DeviceInventory     setOwnerName()                    Sets the current record's "owner_name" value
 * @method DeviceInventory     setOwnerEmail()                   Sets the current record's "owner_email" value
 * @method DeviceInventory     setUdid()                         Sets the current record's "udid" value
 * @method DeviceInventory     setImei()                         Sets the current record's "imei" value
 * @method DeviceInventory     setWifiMacAddress()               Sets the current record's "wifi_mac_address" value
 * @method DeviceInventory     setPasscode()                     Sets the current record's "passcode" value
 * @method DeviceInventory     setModel()                        Sets the current record's "model" value
 * @method DeviceInventory     setDeviceInventories()            Sets the current record's "DeviceInventories" collection
 * @method DeviceInventory     setDeviceEventInventories()       Sets the current record's "DeviceEventInventories" collection
 * @method DeviceInventory     setDeviceApplicationInventories() Sets the current record's "DeviceApplicationInventories" collection
 * @method DeviceInventory     setDeviceLocationInventories()    Sets the current record's "DeviceLocationInventories" collection
 * @method DeviceInventory     setDeviceProfiles()               Sets the current record's "DeviceProfiles" collection
 * 
 * @package    mdm-server
 * @subpackage model
 * @author     Dung Huynh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDeviceInventory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('device_inventory');
        $this->hasColumn('device_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('manufacturer', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('product_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('device_type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('registration_id', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('enroll_status', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('version', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('organization', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('location', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('platform', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('purchase_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('warranty_end', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('owner_name', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('owner_email', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('udid', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
        $this->hasColumn('imei', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
        $this->hasColumn('wifi_mac_address', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
        $this->hasColumn('passcode', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('model', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('InventoryInformation as DeviceInventories', array(
             'local' => 'id',
             'foreign' => 'device_id'));

        $this->hasMany('DeviceEvent as DeviceEventInventories', array(
             'local' => 'id',
             'foreign' => 'device_id'));

        $this->hasMany('DeviceApplication as DeviceApplicationInventories', array(
             'local' => 'id',
             'foreign' => 'device_id'));

        $this->hasMany('DeviceLocation as DeviceLocationInventories', array(
             'local' => 'id',
             'foreign' => 'device_id'));

        $this->hasMany('DeviceProfile as DeviceProfiles', array(
             'local' => 'id',
             'foreign' => 'device_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}