<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ProfileInformation', 'mdmserver');

/**
 * BaseProfileInformation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $profile_id
 * @property text $value
 * @property integer $profile_attribute_group_id
 * @property Profile $Profile
 * @property ProfileAttributeGroup $ProfileAttributeGroup
 * 
 * @method integer               getProfileId()                  Returns the current record's "profile_id" value
 * @method text                  getValue()                      Returns the current record's "value" value
 * @method integer               getProfileAttributeGroupId()    Returns the current record's "profile_attribute_group_id" value
 * @method Profile               getProfile()                    Returns the current record's "Profile" value
 * @method ProfileAttributeGroup getProfileAttributeGroup()      Returns the current record's "ProfileAttributeGroup" value
 * @method ProfileInformation    setProfileId()                  Sets the current record's "profile_id" value
 * @method ProfileInformation    setValue()                      Sets the current record's "value" value
 * @method ProfileInformation    setProfileAttributeGroupId()    Sets the current record's "profile_attribute_group_id" value
 * @method ProfileInformation    setProfile()                    Sets the current record's "Profile" value
 * @method ProfileInformation    setProfileAttributeGroup()      Sets the current record's "ProfileAttributeGroup" value
 * 
 * @package    mdm-server
 * @subpackage model
 * @author     Dung Huynh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfileInformation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profile_information');
        $this->hasColumn('profile_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('value', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('profile_attribute_group_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Profile', array(
             'local' => 'profile_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ProfileAttributeGroup', array(
             'local' => 'profile_attribute_group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}