<?php

/**
 * BaseCommand
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $device_id
 * @property string $name
 * @property integer $status
 * @property DeviceInventory $DeviceInventory
 * 
 * @method integer         getDeviceId()        Returns the current record's "device_id" value
 * @method string          getName()            Returns the current record's "name" value
 * @method integer         getStatus()          Returns the current record's "status" value
 * @method DeviceInventory getDeviceInventory() Returns the current record's "DeviceInventory" value
 * @method Command         setDeviceId()        Sets the current record's "device_id" value
 * @method Command         setName()            Sets the current record's "name" value
 * @method Command         setStatus()          Sets the current record's "status" value
 * @method Command         setDeviceInventory() Sets the current record's "DeviceInventory" value
 * 
 * @package    mdm-server
 * @subpackage model
 * @author     Dung Huynh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCommand extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('command');
        $this->hasColumn('device_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('status', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DeviceInventory', array(
             'local' => 'device_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}