<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DeviceOwner', 'mdmserver');

/**
 * BaseDeviceOwner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $owner_id
 * @property integer $device_id
 * @property DeviceInventory $DeviceInventory
 * 
 * @method integer         getOwnerId()         Returns the current record's "owner_id" value
 * @method integer         getDeviceId()        Returns the current record's "device_id" value
 * @method DeviceInventory getDeviceInventory() Returns the current record's "DeviceInventory" value
 * @method DeviceOwner     setOwnerId()         Sets the current record's "owner_id" value
 * @method DeviceOwner     setDeviceId()        Sets the current record's "device_id" value
 * @method DeviceOwner     setDeviceInventory() Sets the current record's "DeviceInventory" value
 * 
 * @package    mdm-server
 * @subpackage model
 * @author     Dung Huynh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDeviceOwner extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('device_owner');
        $this->hasColumn('owner_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('device_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DeviceInventory', array(
             'local' => 'device_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}