<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Location', 'mdmserver');

/**
 * BaseLocation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $location
 * @property string $organization
 * 
 * @method string   getLocation()     Returns the current record's "location" value
 * @method string   getOrganization() Returns the current record's "organization" value
 * @method Location setLocation()     Sets the current record's "location" value
 * @method Location setOrganization() Sets the current record's "organization" value
 * 
 * @package    mdm-server
 * @subpackage model
 * @author     Dung Huynh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLocation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('location');
        $this->hasColumn('location', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('organization', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}