<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Template', 'mdmserver');

/**
 * BaseTemplate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property text $content
 * @property integer $usage_system
 * @property integer $tenant_id
 * @property string $subject
 * 
 * @method string   getName()         Returns the current record's "name" value
 * @method text     getContent()      Returns the current record's "content" value
 * @method integer  getUsageSystem()  Returns the current record's "usage_system" value
 * @method integer  getTenantId()     Returns the current record's "tenant_id" value
 * @method string   getSubject()      Returns the current record's "subject" value
 * @method Template setName()         Sets the current record's "name" value
 * @method Template setContent()      Sets the current record's "content" value
 * @method Template setUsageSystem()  Sets the current record's "usage_system" value
 * @method Template setTenantId()     Sets the current record's "tenant_id" value
 * @method Template setSubject()      Sets the current record's "subject" value
 * 
 * @package    mdm-server
 * @subpackage model
 * @author     Dung Huynh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTemplate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('template');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('content', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('usage_system', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('tenant_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('subject', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}