<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ProfileAttributeGroup', 'mdmserver');

/**
 * BaseProfileAttributeGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $ProfileAttributeGroups
 * 
 * @method string                getName()                   Returns the current record's "name" value
 * @method Doctrine_Collection   getProfileAttributeGroups() Returns the current record's "ProfileAttributeGroups" collection
 * @method ProfileAttributeGroup setName()                   Sets the current record's "name" value
 * @method ProfileAttributeGroup setProfileAttributeGroups() Sets the current record's "ProfileAttributeGroups" collection
 * 
 * @package    mdm-server
 * @subpackage model
 * @author     Dung Huynh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfileAttributeGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profile_attribute_group');
        $this->hasColumn('name', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ProfileAttribute as ProfileAttributeGroups', array(
             'local' => 'id',
             'foreign' => 'profile_attribute_group_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}