<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DeviceLocation', 'mdmserver');

/**
 * BaseDeviceLocation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $device_id
 * @property string $latitude
 * @property string $longitude
 * @property string $address
 * @property DeviceInventory $DeviceInventory
 * 
 * @method integer         getDeviceId()        Returns the current record's "device_id" value
 * @method string          getLatitude()        Returns the current record's "latitude" value
 * @method string          getLongitude()       Returns the current record's "longitude" value
 * @method string          getAddress()         Returns the current record's "address" value
 * @method DeviceInventory getDeviceInventory() Returns the current record's "DeviceInventory" value
 * @method DeviceLocation  setDeviceId()        Sets the current record's "device_id" value
 * @method DeviceLocation  setLatitude()        Sets the current record's "latitude" value
 * @method DeviceLocation  setLongitude()       Sets the current record's "longitude" value
 * @method DeviceLocation  setAddress()         Sets the current record's "address" value
 * @method DeviceLocation  setDeviceInventory() Sets the current record's "DeviceInventory" value
 * 
 * @package    mdm-server
 * @subpackage model
 * @author     Dung Huynh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDeviceLocation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('device_location');
        $this->hasColumn('device_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('latitude', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('longitude', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('address', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DeviceInventory', array(
             'local' => 'device_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}