<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('InventoryAttribute', 'mdmserver');

/**
 * BaseInventoryAttribute
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $slug
 * @property integer $inventory_group_id
 * @property InventoryAttributeGroup $InventoryAttributeGroup
 * 
 * @method string                  getName()                    Returns the current record's "name" value
 * @method string                  getSlug()                    Returns the current record's "slug" value
 * @method integer                 getInventoryGroupId()        Returns the current record's "inventory_group_id" value
 * @method InventoryAttributeGroup getInventoryAttributeGroup() Returns the current record's "InventoryAttributeGroup" value
 * @method InventoryAttribute      setName()                    Sets the current record's "name" value
 * @method InventoryAttribute      setSlug()                    Sets the current record's "slug" value
 * @method InventoryAttribute      setInventoryGroupId()        Sets the current record's "inventory_group_id" value
 * @method InventoryAttribute      setInventoryAttributeGroup() Sets the current record's "InventoryAttributeGroup" value
 * 
 * @package    mdm-server
 * @subpackage model
 * @author     Dung Huynh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInventoryAttribute extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('inventory_attribute');
        $this->hasColumn('name', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 250,
             ));
        $this->hasColumn('slug', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('inventory_group_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('InventoryAttributeGroup', array(
             'local' => 'inventory_group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}