<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Role', 'mcenter');

/**
 * BaseRole
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $role_id
 * @property string $role_name
 * @property Doctrine_Collection $Roles
 * 
 * @method integer             getRoleId()    Returns the current record's "role_id" value
 * @method string              getRoleName()  Returns the current record's "role_name" value
 * @method Doctrine_Collection getRoles()     Returns the current record's "Roles" collection
 * @method Role                setRoleId()    Sets the current record's "role_id" value
 * @method Role                setRoleName()  Sets the current record's "role_name" value
 * @method Role                setRoles()     Sets the current record's "Roles" collection
 * 
 * @package    mdm-server
 * @subpackage model
 * @author     Dung Huynh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRole extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('role');
        $this->hasColumn('role_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('role_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('UserInfo as Roles', array(
             'local' => 'id',
             'foreign' => 'role_id'));
    }
}