<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('InventoryAttributeGroup', 'mdmserver');

/**
 * BaseInventoryAttributeGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $InventoryAttributeGroups
 * 
 * @method string                  getName()                     Returns the current record's "name" value
 * @method Doctrine_Collection     getInventoryAttributeGroups() Returns the current record's "InventoryAttributeGroups" collection
 * @method InventoryAttributeGroup setName()                     Sets the current record's "name" value
 * @method InventoryAttributeGroup setInventoryAttributeGroups() Sets the current record's "InventoryAttributeGroups" collection
 * 
 * @package    mdm-server
 * @subpackage model
 * @author     Dung Huynh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInventoryAttributeGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('inventory_attribute_group');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('InventoryAttribute as InventoryAttributeGroups', array(
             'local' => 'id',
             'foreign' => 'inventory_group_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}