<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Profile', 'mdmserver');

/**
 * BaseProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $profile_name
 * @property integer $platform
 * @property integer $configuration_type
 * @property string $description
 * @property Doctrine_Collection $ProfileInventories
 * @property Doctrine_Collection $ProfileDevices
 * 
 * @method string              getProfileName()        Returns the current record's "profile_name" value
 * @method integer             getPlatform()           Returns the current record's "platform" value
 * @method integer             getConfigurationType()  Returns the current record's "configuration_type" value
 * @method string              getDescription()        Returns the current record's "description" value
 * @method Doctrine_Collection getProfileInventories() Returns the current record's "ProfileInventories" collection
 * @method Doctrine_Collection getProfileDevices()     Returns the current record's "ProfileDevices" collection
 * @method Profile             setProfileName()        Sets the current record's "profile_name" value
 * @method Profile             setPlatform()           Sets the current record's "platform" value
 * @method Profile             setConfigurationType()  Sets the current record's "configuration_type" value
 * @method Profile             setDescription()        Sets the current record's "description" value
 * @method Profile             setProfileInventories() Sets the current record's "ProfileInventories" collection
 * @method Profile             setProfileDevices()     Sets the current record's "ProfileDevices" collection
 * 
 * @package    mdm-server
 * @subpackage model
 * @author     Dung Huynh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profile');
        $this->hasColumn('profile_name', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('platform', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('configuration_type', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('description', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ProfileInformation as ProfileInventories', array(
             'local' => 'id',
             'foreign' => 'profile_id'));

        $this->hasMany('DeviceProfile as ProfileDevices', array(
             'local' => 'id',
             'foreign' => 'profile_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}