<?php

/**
 * DeviceApplication
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mdm-server
 * @subpackage model
 * @author     Dung Huynh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class DeviceApplication extends BaseDeviceApplication
{
}
