<?php

/**
 * DeviceLocationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DeviceLocationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DeviceLocationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DeviceLocation');
    }
}