<?php

/**
 * DeviceInventory
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    mdm-server
 * @subpackage model
 * @author     Dung Huynh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class DeviceInventory extends BaseDeviceInventory {

    /**
     * @return string
     */
    public function getEnrollStatusName() {
        $enroll_statuses = \sfConfig::get("app_enroll_statuses_data");
        $enroll_status = $this->getEnrollStatus();
        return empty($enroll_statuses[$enroll_status]) ? 'Undefined' : $enroll_statuses[$enroll_status];
    }

    /**
     * @return string
     */
    public function getPlatformSlug() {
        $platform = $this->getPlatform();
        switch ($platform) {
            case 1: $device_platform = 'android';
                break;
            case 2: $device_platform = 'ios';
                break;
            case 3: $device_platform = 'wp';
                break;
            default: $device_platform = 'ios';
                break;
        }
        return $device_platform;
    }

    public function getActivities() {
        $deviceEventTableTable = \DeviceEventTable::getInstance();
        $q = $deviceEventTableTable->createQuery('a')
                ->where('device_id = ?', $this->id)
                ->orderBy('a.created_at DESC');
        return $q->execute();
    }

    // Date format to appear
    function getDateFormat($date) {
//        $format = 'M j, Y';
        $format = 'Y-m-d';
        if (empty($date)) {
            return '';
        }
        return date($format, strtotime($date));
    }

}
