<?php

/**
 * DeviceEvent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mdm-server
 * @subpackage model
 * @author     Dung Huynh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class DeviceEvent extends BaseDeviceEvent
{
    /**
     * @return string
     */
    public function getEventStatusName() {
        $status= \sfConfig::get("app_event_status_data");
        $even_status = $this->getStatus();
        return empty($status[$even_status]) ? 'Undefined' : $status[$even_status];
    }
    /**
     * @return string
     */
    public function getEventNameView() {
        $name= \sfConfig::get("app_event_name_data");
        $even_name = $this->getEventName();
        return empty($name[$even_name]) ? 'Undefined' : $name[$even_name];
    }
}
