<?php

/**
 * DeviceApplicationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DeviceApplicationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DeviceApplicationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DeviceApplication');
    }
}