<?php

/**
 * InventoryInformationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InventoryInformationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InventoryInformationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InventoryInformation');
    }
}