<?php

/**
 * Profile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mdm-server
 * @subpackage model
 * @author     Dung Huynh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Profile extends BaseProfile {

    /**
     * 
     * @return array
     */
    public function configTypeDefault(){
        return \sfConfig::get("app_configuration_type_data");
    }
    
    public function getConfigTypeName() {
        $name = \sfConfig::get("app_configuration_type_data");
        $status = $this->getConfigurationType();
        return empty($name[$status]) ? 'Undefined' : $name[$status];
    }
    
    /**
     * 
     * @return array
     */
    public function platformNameDefault(){
        return \sfConfig::get("app_platforms_data");
    }
    
    public function getPlatformName() {
        $name = \sfConfig::get("app_platforms_data");
        $status = $this->getPlatform();
        return empty($name[$status]) ? 'Undefined' : $name[$status];
    }

}
