<?php

/**
 * ProfileInformationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileInformationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfileInformationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfileInformation');
    }
}