<?php

/**
 * Template
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mdm-server
 * @subpackage model
 * @author     Dung Huynh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Template extends BaseTemplate
{
    /**
     * 
     * @return array
     */
    public function usageSystemDefault(){
        return \sfConfig::get("app_template_usage_data");
    }

    /**
     * @return string
     */
    public function getTemplateUsageSystem() {
        $template_usages = $this->usageSystemDefault();
        $template_usage = $this->getUsageSystem();
        return empty($template_usages[$template_usage]) ? 'Undefined' : $template_usages[$template_usage];
    }
}