<?php

/**
 * TemplateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TemplateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TemplateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Template');
    }
}