<?php

/**
 * UserInfo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mdm-server
 * @subpackage model
 * @author     Dung Huynh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UserInfo extends BaseUserInfo
{
    function getFullName() {
        return $this->getFirstName(). ' ' . $this->getLastName();
    }
    function getBirthdayInFormat($format = 'M j, Y') {
        $birthday = $this->getBirthday();
        if (empty($birthday)) return '';
        return date($format, strtotime($birthday));
    }
    function setBirthdayInFormat($date = null, $format = 'Y-m-d') {
        $this->setBirthday(empty($date) ? null : date($format, strtotime($date)));
    }
    function setPasswordInHash($password = '') {
        $this->setPassword($this->getHashedPassword($password));
    }
    function getHashedPassword($password = '') {
        return sha1( $password . md5($password) ) . ':' . md5($password);
    }
}
