<?php

/**
 * UserInfoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */


class UserInfoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserInfoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserInfo');
    }
}